### ISSUE TITLE
Configure autouse for cleanup fixtures

### ISSUE THREAD

**Issue by extsoft** [shitikovkirill/pbc-PythonBootCamp#28]
https://github.com/shitikovkirill/pbc-PythonBootCamp/blob/9a3f32602a84a2a2b2f19d62f64e0df294f19df1/pbc/selenium/tests/conftest.py#L18

https://github.com/shitikovkirill/pbc-PythonBootCamp/blob/9a3f32602a84a2a2b2f19d62f64e0df294f19df1/pbc/selenium/tests/conftest.py#L26

And do not pass them to the test functions.

**Comment by shitikovkirill** [comment]
5fab22d4d157b20d7c225ff5952a67b974ee8e8d
